# Etapa 1: Usar uma imagem base com Maven
FROM maven:3.8.4-openjdk-17 as build

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o pom.xml e o código-fonte para o container
COPY pom.xml .
COPY src ./src

# Rodar o Maven para gerar o arquivo JAR
RUN mvn clean package -DskipTests

# Etapa 2: Usar uma imagem leve para rodar a aplicação
FROM amazoncorretto:17

# Copiar o arquivo JAR gerado na etapa de build para o container final
COPY --from=build /app/target/*.jar /application.jar

# Definir o comando de execução
ENTRYPOINT ["java", "-Xmx2048M", "-jar", "/application.jar"]
